name: Flutter CI/CD Clean Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kodu çek
      - name: Check out code
        uses: actions/checkout@v3

      # Flutter ortamını kur
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'

      # Repo root klasörünü kontrol et
      - name: Show repo structure
        run: ls -R

      # Clean build
      - name: Clean previous builds
        working-directory: ./Asgard  # checkout sonrası repo klasörü
        run: flutter clean

      # Dependencies yükle
      - name: Flutter pub get
        working-directory: ./Asgard
        run: flutter pub get

      # Testleri çalıştır
      - name: Run tests
        working-directory: ./Asgard
        run: flutter test

      # APK build et
      - name: Build APK
        working-directory: ./Asgard
        run: flutter build apk --release

      # APK’yı artifacts olarak kaydet
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./Asgard/build/app/outputs/flutter-apk/app-release.apk